# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows:
1. The first a random number from 1 to 4
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [2]:
s1 = pd.Series(np.random.randint(1, 5, 100))
s1

0     2
1     4
2     3
3     2
4     1
     ..
95    4
96    3
97    3
98    3
99    3
Length: 100, dtype: int64

In [3]:
s2 = pd.Series(np.random.randint(1, 4, 100))
s2

0     1
1     3
2     2
3     2
4     1
     ..
95    1
96    3
97    3
98    1
99    1
Length: 100, dtype: int64

In [4]:
s3 = pd.Series(np.random.randint(10000, 30001, 100))
s3

0     15673
1     16216
2     18551
3     23599
4     27544
      ...
95    12910
96    21833
97    12292
98    23871
99    12054
Length: 100, dtype: int64

### Step 3. Let's create a DataFrame by joinning the Series by column

In [5]:
join_series = pd.concat([s1, s2, s3], axis = 1)
join_series

    0  1      2
0   2  1  15673
1   4  3  16216
2   3  2  18551
3   2  2  23599
4   1  1  27544
.. .. ..    ...
95  4  1  12910
96  3  3  21833
97  3  3  12292
98  3  1  23871
99  3  1  12054

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [6]:
join_series.columns = ['bedrs', 'bathrs', 'price_sqr_meter']
join_series

    bedrs  bathrs  price_sqr_meter
0       2       1            15673
1       4       3            16216
2       3       2            18551
3       2       2            23599
4       1       1            27544
..    ...     ...              ...
95      4       1            12910
96      3       3            21833
97      3       3            12292
98      3       1            23871
99      3       1            12054

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [7]:
bigcolumn = pd.DataFrame(pd.concat([s1, s2, s3], axis = 0) , columns = ["bigcolumn"])
bigcolumn

    bigcolumn
0           2
1           4
2           3
3           2
4           1
..        ...
95      12910
96      21833
97      12292
98      23871
99      12054

[300 rows x 1 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

Yes, because I did not reset the index; when series are concatenated in python pandas keeps their original 0 - 99 indices, so they will
repeat three times even though the result has 300 rows.

In [8]:
len(bigcolumn)

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [9]:
bigcolumn.reset_index(drop = True , inplace = True)
bigcolumn

     bigcolumn
0            2
1            4
2            3
3            2
4            1
..         ...
295      12910
296      21833
297      12292
298      23871
299      12054

[300 rows x 1 columns]