# Investor - Flow of Funds - US

### Introduction:

Special thanks to: https://github.com/rgrp for sharing the dataset.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv).

### Step 3. Assign it to a variable called

In [2]:
investor = pd.read_csv("https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv")
investor.head()

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2022-07-06,10167,NaN,3058,NaN,842,NaN,2216,NaN
1,2022-07-13,7409,NaN,2808,NaN,2067,NaN,741,NaN
2,2022-07-20,3468,NaN,102,NaN,-417,NaN,519,NaN
3,2022-07-27,14213,NaN,9667,NaN,8598,NaN,1069,NaN
4,2022-08-03,9786,NaN,4016,NaN,3079,NaN,937,NaN

### Step 4.  What is the frequency of the dataset?

* Weekly as we can see that each row corresponds to a one-week interval. Also the file name is ....weekly.csv

### Step 5. Set the column Date as the index.

In [3]:
investor = investor.set_index("Date")
investor.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-06,10167,NaN,3058,NaN,842,NaN,2216,NaN
2022-07-13,7409,NaN,2808,NaN,2067,NaN,741,NaN
2022-07-20,3468,NaN,102,NaN,-417,NaN,519,NaN
2022-07-27,14213,NaN,9667,NaN,8598,NaN,1069,NaN
2022-08-03,9786,NaN,4016,NaN,3079,NaN,937,NaN

### Step 6. What is the type of the index?

In [4]:
investor.index.dtype

dtype('O')

### Step 7. Set the index to a DatetimeIndex type

In [5]:
investor.index = pd.to_datetime(investor.index)
investor.index.dtype

dtype('<M8[ns]')

### Step 8.  Change the frequency to monthly, sum the values and assign it to monthly.

In [6]:
monthly = investor.resample('M').sum()
monthly.head()

/tmp/ipykernel_3043/3317727790.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly = investor.resample('M').sum()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-31,35257,0.0,15635,0.0,11090,0.0,4545,0.0
2022-08-31,48596,0.0,32348,0.0,33705,0.0,-1357,0.0
2022-09-30,13775,0.0,10324,0.0,11629,0.0,-1305,0.0
2022-10-31,82879,0.0,55644,0.0,47435,0.0,8209,0.0
2022-11-30,82731,0.0,54314,0.0,37348,0.0,16967,0.0

### Step 9. You will notice that it filled the dataFrame with months that don't have any data with NaN. Let's drop these rows.

In [7]:
monthly = monthly.dropna(how='all')
monthly.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-31,35257,0.0,15635,0.0,11090,0.0,4545,0.0
2022-08-31,48596,0.0,32348,0.0,33705,0.0,-1357,0.0
2022-09-30,13775,0.0,10324,0.0,11629,0.0,-1305,0.0
2022-10-31,82879,0.0,55644,0.0,47435,0.0,8209,0.0
2022-11-30,82731,0.0,54314,0.0,37348,0.0,16967,0.0

### Step 10. Good, now we have the monthly data. Now change the frequency to year.

In [8]:
yearly = monthly.resample('Y').sum()
yearly.head()

/tmp/ipykernel_3043/3026375306.py:1: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  yearly = monthly.resample('Y').sum()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-12-31,303689,0.0,197389,0.0,159480,0.0,37908,0.0
2023-12-31,577223,0.0,384006,0.0,301790,0.0,82214,0.0
2024-12-31,501341,0.0,362632,0.0,312430,0.0,50200,0.0
2025-12-31,204465,0.0,126778,0.0,90915,0.0,35862,0.0
2026-12-31,296299,0.0,177177,0.0,85818,0.0,91358,0.0

### BONUS: Create your own question and answer it.

**Which year had the highest total net inflow across all fund categories?**

In [9]:
high_year = yearly['Total'].idxmax()
print("The highest yearly total was in:", high_year)

The highest yearly total was in: 2022-12-31 00:00:00