# Getting Financial Data - Pandas Datareader

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import pandas_datareader.data as web
import datetime as dt
import yfinance as yf

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is).

In [2]:
start_date = dt.datetime(2015, 1, 1)
end_date = dt.datetime.today()
start_date, end_date

(datetime.datetime(2015, 1, 1, 0, 0),
 datetime.datetime(2026, 4, 18, 15, 41, 43, 894481))

### Step 3. Get an API key for one of the APIs that are supported by Pandas Datareader, preferably for AlphaVantage.

If you do not have an API key for any of the supported APIs, it is easiest to get one for [AlphaVantage](https://www.alphavantage.co/support/#api-key). (Note that the API key is shown directly after the signup. You do *not* receive it via e-mail.)

(For a full list of the APIs that are supported by Pandas Datareader, [see here](https://pydata.github.io/pandas-datareader/readers/index.html). As the APIs are provided by third parties, this list may change.)

### Step 4. Use Pandas Datarader to read the daily time series for the Apple stock (ticker symbol AAPL) between 01/01/2015 and today, assign it to df_apple and print it.

In [3]:
df_apple = web.DataReader('AAPL', 'av-daily', start_date, end_date, api_key = "3LXU0TIVX945O4D7")
df_apple

RemoteDataError:  Their was an issue from the data vendor side, here is their response: {'Information': 'Thank you for using Alpha Vantage! The outputsize=full parameter value is a premium feature for the TIME_SERIES_DAILY endpoint. You may subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly unlock all premium features'}

**NOTE:** it keeps giving me errors so i used yfinance.

* yfinance code:

In [4]:
df_apple = yf.download("AAPL", start=start_date, end=end_date)
if isinstance(df_apple.columns, pd.MultiIndex):                  #  to fix multiindex columns
  df_apple.columns = df_apple.columns.get_level_values(0)
df_apple

/tmp/ipykernel_1378/1192739375.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_apple = yf.download("AAPL", start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Date
2015-01-02   24.214901   24.682233   23.776361   24.671159  212818400
2015-01-05   23.532726   24.064289   23.346680   23.984555  257142000
2015-01-06   23.534935   23.794071   23.173914   23.596950  263188400
2015-01-07   23.864950   23.964618   23.632391   23.743133  160423600
2015-01-08   24.781887   24.839473   24.075351   24.192739  237458000
...                ...         ...         ...         ...        ...
2026-04-13  259.200012  260.179993  256.660004  259.730011   36234700
2026-04-14  258.829987  261.929993  257.190002  259.250000   48370700
2026-04-15  266.429993  266.559998  257.809998  258.160004   49913500
2026-04-16  263.399994  267.160004  261.269989  266.799988   43323100
2026-04-17  270.230011  272.299988  266.720001  266.959991   61314800

[2839 rows x 5 columns]

### Step 5. Add a new column "stock" to the dataframe and add the ticker symbol

In [5]:
df_apple["stock"] = "AAPL"
df_apple

Price            Close        High         Low        Open     Volume stock
Date
2015-01-02   24.214901   24.682233   23.776361   24.671159  212818400  AAPL
2015-01-05   23.532726   24.064289   23.346680   23.984555  257142000  AAPL
2015-01-06   23.534935   23.794071   23.173914   23.596950  263188400  AAPL
2015-01-07   23.864950   23.964618   23.632391   23.743133  160423600  AAPL
2015-01-08   24.781887   24.839473   24.075351   24.192739  237458000  AAPL
...                ...         ...         ...         ...        ...   ...
2026-04-13  259.200012  260.179993  256.660004  259.730011   36234700  AAPL
2026-04-14  258.829987  261.929993  257.190002  259.250000   48370700  AAPL
2026-04-15  266.429993  266.559998  257.809998  258.160004   49913500  AAPL
2026-04-16  263.399994  267.160004  261.269989  266.799988   43323100  AAPL
2026-04-17  270.230011  272.299988  266.720001  266.959991   61314800  AAPL

[2839 rows x 6 columns]

### Step 6. Repeat the two previous steps for a few other stocks, always creating a new dataframe: Tesla, IBM and Microsoft. (Ticker symbols TSLA, IBM and MSFT.)

In [6]:
df_tesla = yf.download("TSLA", start=start_date, end=end_date)
if isinstance(df_tesla.columns, pd.MultiIndex):
  df_tesla.columns = df_tesla.columns.get_level_values(0)

df_tesla["stock"] = "TSLA"
df_tesla

/tmp/ipykernel_1378/1785238713.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_tesla = yf.download("TSLA", start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume stock
Date
2015-01-02   14.620667   14.883333   14.217333   14.858000   71466000  TSLA
2015-01-05   14.006000   14.433333   13.810667   14.303333   80527500  TSLA
2015-01-06   14.085333   14.280000   13.614000   14.004000   93928500  TSLA
2015-01-07   14.063333   14.318667   13.985333   14.223333   44526000  TSLA
2015-01-08   14.041333   14.253333   14.000667   14.187333   51637500  TSLA
...                ...         ...         ...         ...        ...   ...
2026-04-13  352.420013  356.350006  348.570007  350.070007   53617500  TSLA
2026-04-14  364.200012  367.630005  354.769989  357.670013   59979600  TSLA
2026-04-15  391.950012  394.649994  362.500000  366.829987  113810400  TSLA
2026-04-16  388.899994  394.059998  381.799988  393.809998   63515100  TSLA
2026-04-17  400.619995  409.279999  391.649994  395.920013   90388400  TSLA

[2839 rows x 6 columns]

In [7]:
df_ibm = yf.download("IBM", start=start_date, end=end_date)
if isinstance(df_ibm.columns, pd.MultiIndex):
  df_ibm.columns = df_ibm.columns.get_level_values(0)

df_ibm["stock"] = "IBM"
df_ibm

/tmp/ipykernel_1378/1367857775.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_ibm = yf.download("IBM", start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open   Volume stock
Date
2015-01-02   97.566780   98.319337   96.928618   97.115253  5779673   IBM
2015-01-05   96.031570   97.091164   95.838920   97.091164  5104898   IBM
2015-01-06   93.960533   96.302475   93.418701   96.127880  6429448   IBM
2015-01-07   93.346481   94.640871   92.732399   94.640871  4918083   IBM
2015-01-08   95.375351   95.748612   93.647491   94.062897  4431693   IBM
...                ...         ...         ...         ...      ...   ...
2026-04-13  237.820007  238.070007  231.699997  233.630005  5349600   IBM
2026-04-14  240.270004  241.539993  238.119995  238.750000  3777300   IBM
2026-04-15  244.800003  246.059998  240.990005  242.250000  3879500   IBM
2026-04-16  251.000000  251.220001  246.130005  248.750000  4817500   IBM
2026-04-17  253.470001  255.649994  251.039993  254.669998  5624400   IBM

[2839 rows x 6 columns]

In [8]:
df_microsoft = yf.download("MSFT", start=start_date, end=end_date)
if isinstance(df_microsoft.columns, pd.MultiIndex):
  df_microsoft.columns = df_microsoft.columns.get_level_values(0)

df_microsoft["stock"] = "MSFT"
df_microsoft

/tmp/ipykernel_1378/1799961185.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_microsoft = yf.download("MSFT", start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume stock
Date
2015-01-02   39.767681   40.328987   39.580581   39.682636  27913900  MSFT
2015-01-05   39.401974   39.742157   39.333935   39.435990  39673900  MSFT
2015-01-06   38.823669   39.759178   38.730118   39.444508  36447900  MSFT
2015-01-07   39.316948   39.512554   38.687606   39.104332  29114100  MSFT
2015-01-08   40.473579   40.609654   39.733677   39.759190  29645200  MSFT
...                ...         ...         ...         ...       ...   ...
2026-04-13  384.369995  384.540009  371.019989  373.609985  35745800  MSFT
2026-04-14  393.109985  394.690002  386.519989  387.920013  37504500  MSFT
2026-04-15  411.220001  414.369995  396.730011  398.000000  45063400  MSFT
2026-04-16  420.260010  420.820007  412.140015  419.859985  41642400  MSFT
2026-04-17  422.790009  431.579987  420.690002  424.820007  47812100  MSFT

[2839 rows x 6 columns]

### Step 7. Combine the four separate dataFrames into one combined dataFrame df that holds the information for all four stocks

In [9]:
combined_df = pd.concat([df_apple, df_tesla, df_ibm, df_microsoft])
combined_df

Price            Close        High         Low        Open     Volume stock
Date
2015-01-02   24.214901   24.682233   23.776361   24.671159  212818400  AAPL
2015-01-05   23.532726   24.064289   23.346680   23.984555  257142000  AAPL
2015-01-06   23.534935   23.794071   23.173914   23.596950  263188400  AAPL
2015-01-07   23.864950   23.964618   23.632391   23.743133  160423600  AAPL
2015-01-08   24.781887   24.839473   24.075351   24.192739  237458000  AAPL
...                ...         ...         ...         ...        ...   ...
2026-04-13  384.369995  384.540009  371.019989  373.609985   35745800  MSFT
2026-04-14  393.109985  394.690002  386.519989  387.920013   37504500  MSFT
2026-04-15  411.220001  414.369995  396.730011  398.000000   45063400  MSFT
2026-04-16  420.260010  420.820007  412.140015  419.859985   41642400  MSFT
2026-04-17  422.790009  431.579987  420.690002  424.820007   47812100  MSFT

[11356 rows x 6 columns]

### Step 8. Shift the stock column into the index (making it a multi-level index consisting of the ticker symbol and the date).

In [10]:
combined_df = combined_df.reset_index()
combined_df.set_index(["stock", "Date"], inplace=True)
combined_df

Price                  Close        High         Low        Open     Volume
stock Date
AAPL  2015-01-02   24.214901   24.682233   23.776361   24.671159  212818400
      2015-01-05   23.532726   24.064289   23.346680   23.984555  257142000
      2015-01-06   23.534935   23.794071   23.173914   23.596950  263188400
      2015-01-07   23.864950   23.964618   23.632391   23.743133  160423600
      2015-01-08   24.781887   24.839473   24.075351   24.192739  237458000
...                      ...         ...         ...         ...        ...
MSFT  2026-04-13  384.369995  384.540009  371.019989  373.609985   35745800
      2026-04-14  393.109985  394.690002  386.519989  387.920013   37504500
      2026-04-15  411.220001  414.369995  396.730011  398.000000   45063400
      2026-04-16  420.260010  420.820007  412.140015  419.859985   41642400
      2026-04-17  422.790009  431.579987  420.690002  424.820007   47812100

[11356 rows x 5 columns]

### Step 7. Create a dataFrame called vol, with the volume values.

In [11]:
vol = combined_df[["Volume"]]
vol

Price                Volume
stock Date
AAPL  2015-01-02  212818400
      2015-01-05  257142000
      2015-01-06  263188400
      2015-01-07  160423600
      2015-01-08  237458000
...                     ...
MSFT  2026-04-13   35745800
      2026-04-14   37504500
      2026-04-15   45063400
      2026-04-16   41642400
      2026-04-17   47812100

[11356 rows x 1 columns]

### Step 8. Aggregate the data of volume to weekly.
Hint: Be careful to not sum data from the same week of 2015 and other years.

In [12]:
weekly_volume = vol.groupby(level="stock").resample("W", level="Date").sum().unstack(level="stock")
weekly_volume

Price           Volume
stock             AAPL       IBM       MSFT       TSLA
Date
2015-01-04   212818400   5779673   27913900   71466000
2015-01-11  1133010000  25578884  158825300  340644000
2015-01-18  1216906400  24329751  157088200  461988000
2015-01-25   794948000  32682062  137352600  243175500
2015-02-01  1863370800  34442689  437786800  235803000
...                ...       ...        ...        ...
2026-03-22   223388900  32254900  155862500  301518800
2026-03-29   203871800  21791900  178314900  307356800
2026-04-05   160393100  16212500  143557700  285204300
2026-04-12   191923800  21451600  129201100  344551600
2026-04-19   239156800  23448300  207768200  381311000

[590 rows x 4 columns]

### Step 9. Find all the volume traded in the year of 2015

In [13]:
volume_2015 = vol.loc[pd.IndexSlice[:, '2015'], :].groupby(level="stock").sum()
volume_2015

Price       Volume
stock
AAPL   52264199600
IBM     1156439400
MSFT    9059455900
TSLA   16323267000